# Generated by Django 4.0.4 on 2022-05-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('passengers', '0002_alter_passenger_document_alter_passenger_full_name_and_more'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('travel_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengers.passenger')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
        ),
    ]
