# Generated by Django 4.0.4 on 2022-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=6)),
                ('type', models.CharField(max_length=255)),
                ('capacity', models.SmallIntegerField()),
                ('company', models.CharField(max_length=255)),
            ],
        ),
    ]
