# Generated by Django 4.0.4 on 2022-05-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='plate',
            field=models.CharField(max_length=7),
        ),
    ]
