# Generated by Django 4.0.4 on 2022-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(max_length=255)),
                ('document', models.TextField(max_length=11)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.TextField(max_length=11)),
                ('password', models.TextField(max_length=255)),
            ],
        ),
    ]
