# Generated by Django 4.0.4 on 2022-05-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='document',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
